[project]
name = "ml_framework_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "fastapi>=0.115.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "uvicorn[standard]>=0.34.0",
]

[project.scripts]
diamonds-regression = "ml_framework_project.main:diamonds_regression_entrypoint"
diamonds-classification = "ml_framework_project.main:diamonds_classification_entrypoint"

[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=26.1.0",
    "build>=1.4.0",
    "flake8>=7.3.0",
    "pylint>=4.0.4",
    "pytest>=9.0.2",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
format = "black ."
format-check = "black --check ."
flake = "flake8 ./ml_framework_project"
pylint = "pylint ./ml_framework_project"
build = "python -m build"
test = "uv run pytest --cov=ml_framework_project --cov-report=term-missing"